
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'DBC8FE2883BF679079BF071DCE395C5B'
    
_lr_action_items = {'QUOTE':([0,2,3,5,7,8,10,12,15,16,18,22,23,24,25,26,33,34,39,40,],[1,-18,-19,-22,-20,-17,-24,-23,1,-5,1,1,-11,-13,-12,-10,-6,-16,-14,-15,]),'$end':([0,2,3,5,6,7,8,9,10,12,13,14,16,33,34,35,39,40,],[-21,-18,-19,-22,-2,-20,-17,-4,-24,-23,0,-1,-5,-6,-16,-3,-14,-15,]),'NUM':([0,2,3,5,7,8,10,12,15,16,18,22,23,24,25,26,30,31,33,34,36,39,40,],[3,-18,-19,-22,-20,-17,-24,-23,3,-5,3,3,-11,-13,-12,-10,36,37,-6,-16,38,-14,-15,]),'LPAREN':([0,1,2,3,4,5,7,8,10,11,12,15,16,18,19,22,23,24,25,26,33,34,39,40,],[4,15,-18,-19,17,-22,-20,-17,-24,21,-23,17,-5,17,17,17,-11,-13,-12,-10,-6,-16,-14,-15,]),'TRUE':([0,2,3,5,7,8,10,12,15,16,18,20,22,23,24,25,26,33,34,39,40,],[5,-18,-19,-22,-20,-17,-24,-23,5,-5,5,5,5,-11,-13,-12,-10,-6,-16,-14,-15,]),'TEXT':([0,2,3,5,7,8,10,12,15,16,18,22,23,24,25,26,33,34,39,40,],[7,-18,-19,-22,-20,-17,-24,-23,7,-5,7,7,-11,-13,-12,-10,-6,-16,-14,-15,]),'RPAREN':([2,3,5,7,8,10,12,15,16,18,22,23,24,25,26,27,28,29,32,33,34,37,38,39,40,],[-18,-19,-22,-20,-17,-24,-23,-9,-5,-9,-9,-11,-8,-12,-10,33,34,35,-7,-6,-16,39,40,-14,-15,]),'SIMB':([0,2,3,4,5,7,8,10,12,15,16,17,18,21,22,23,24,25,26,33,34,39,40,],[8,-18,-19,18,-22,-20,-17,-24,-23,8,-5,18,8,31,8,-11,-13,-12,-10,-6,-16,-14,-15,]),'NIL':([0,2,3,5,7,8,10,12,15,16,18,22,23,24,25,26,33,34,39,40,],[10,-18,-19,-22,-20,-17,-24,-23,10,-5,10,10,-11,-13,-12,-10,-6,-16,-14,-15,]),'LET':([0,2,3,4,5,7,8,10,12,15,16,18,19,22,23,24,25,26,33,34,39,40,],[11,-18,-19,11,-22,-20,-17,-24,-23,11,-5,11,11,11,-11,-13,-12,-10,-6,-16,-14,-15,]),'FALSE':([0,2,3,5,7,8,10,12,15,16,18,20,22,23,24,25,26,33,34,39,40,],[12,-18,-19,-22,-20,-17,-24,-23,12,-5,12,12,12,-11,-13,-12,-10,-6,-16,-14,-15,]),'IF':([4,17,],[20,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'item':([15,18,22,],[22,22,22,]),'bool':([0,15,18,20,22,],[2,2,2,30,2,]),'quoted_list':([0,15,18,22,],[6,23,23,23,]),'list':([1,],[16,]),'empty':([15,18,22,],[24,24,24,]),'call':([0,4,15,18,19,22,],[9,19,25,25,29,25,]),'exp':([0,],[13,]),'atom':([0,15,18,22,],[14,26,26,26,]),'items':([15,18,22,],[27,28,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> atom','exp',1,'p_exp_atom','yacc.py',129),
  ('exp -> quoted_list','exp',1,'p_exp_qlist','yacc.py',133),
  ('exp -> LPAREN call call RPAREN','exp',4,'p_exp_2call','yacc.py',137),
  ('exp -> call','exp',1,'p_exp_call','yacc.py',142),
  ('quoted_list -> QUOTE list','quoted_list',2,'p_quoted_list','yacc.py',146),
  ('list -> LPAREN items RPAREN','list',3,'p_list','yacc.py',150),
  ('items -> item items','items',2,'p_items','yacc.py',154),
  ('items -> empty','items',1,'p_items_empty','yacc.py',158),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',162),
  ('item -> atom','item',1,'p_item_atom','yacc.py',166),
  ('item -> quoted_list','item',1,'p_item_list','yacc.py',174),
  ('item -> call','item',1,'p_item_call','yacc.py',178),
  ('item -> empty','item',1,'p_item_empty','yacc.py',182),
  ('call -> LET LPAREN SIMB NUM RPAREN','call',5,'p_call_let','yacc.py',186),
  ('call -> LPAREN IF bool NUM NUM RPAREN','call',6,'p_call_if','yacc.py',190),
  ('call -> LPAREN SIMB items RPAREN','call',4,'p_call','yacc.py',197),
  ('atom -> SIMB','atom',1,'p_atom_simbol','yacc.py',202),
  ('atom -> bool','atom',1,'p_atom_bool','yacc.py',210),
  ('atom -> NUM','atom',1,'p_atom_num','yacc.py',214),
  ('atom -> TEXT','atom',1,'p_atom_word','yacc.py',218),
  ('atom -> <empty>','atom',0,'p_atom_empty','yacc.py',222),
  ('bool -> TRUE','bool',1,'p_true','yacc.py',226),
  ('bool -> FALSE','bool',1,'p_false','yacc.py',230),
  ('atom -> NIL','atom',1,'p_nil','yacc.py',234),
]
